#!/bin/bash
# Guia de Reinstalação - GitHub MCP Server Add-on
# Após correções de bugs

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  GitHub MCP Server Add-on - Reinstalação Corrigida            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Correções aplicadas:"
echo "  • Removida dependência de ghcr.io (build local)"
echo "  • Ativado acesso Docker API"
echo "  • Reescrito run.sh sem bashio"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 1: Desinstalar versão antiga (se existir)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "No Home Assistant:"
echo "  1. Ir a: Supervisor → Add-ons"
echo "  2. Encontrar: GitHub MCP Server"
echo "  3. Clicar: Uninstall (se já instalado)"
echo ""
read -p "Pressione ENTER após desinstalar (ou se não estava instalado)..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 2: Verificar ficheiros corrigidos"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Verificar se as correções foram aplicadas
if grep -q '"docker_api": true' config.json; then
    echo "✅ config.json - docker_api: true"
else
    echo "❌ config.json - docker_api ainda false!"
fi

if grep -q '"image"' config.json; then
    echo "❌ config.json - ainda tem referência 'image'"
else
    echo "✅ config.json - sem referência a 'image'"
fi

if head -1 run.sh | grep -q "#!/bin/bash"; then
    echo "✅ run.sh - usa bash normal"
else
    echo "❌ run.sh - ainda usa bashio!"
fi

if grep -q "/data/options.json" run.sh; then
    echo "✅ run.sh - lê configuração de JSON"
else
    echo "❌ run.sh - não lê options.json!"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 3: Copiar para Home Assistant (se necessário)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Se está a executar localmente, precisa copiar para HAOS:"
echo ""
echo "  scp -r /addons/github-mcp-server root@homeassistant.local:/addons/"
echo ""
echo "Se JÁ está no HAOS, não precisa fazer nada."
echo ""
read -p "Pressione ENTER para continuar..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 4: Recarregar add-ons no Home Assistant"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "No Home Assistant:"
echo "  1. Supervisor → Add-on Store"
echo "  2. Clicar no menu (⋮) no canto superior direito"
echo "  3. Selecionar: 'Check for updates'"
echo "  4. Aguardar reload..."
echo ""
read -p "Pressione ENTER após reload..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 5: Instalar add-on"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "No Home Assistant:"
echo "  1. Scroll down até 'Local add-ons' section"
echo "  2. Encontrar: 'GitHub MCP Server'"
echo "  3. Clicar no add-on"
echo "  4. Clicar: INSTALL"
echo ""
echo "⏳ AGUARDAR BUILD (pode demorar 3-5 minutos)"
echo ""
echo "Durante o build, verá mensagens como:"
echo "  - Downloading dependencies..."
echo "  - Building Docker image..."
echo "  - Installing Python packages..."
echo ""
read -p "Pressione ENTER após instalação completa..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 6: Configurar token GitHub"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "No add-on instalado:"
echo "  1. Clicar na tab: Configuration"
echo "  2. Inserir configuração:"
echo ""
echo "     github_token: ghp_seu_token_aqui"
echo "     toolsets: repos,issues,pull_requests,projects"
echo "     port: 8080"
echo "     log_level: info"
echo ""
echo "  3. Clicar: SAVE"
echo ""
read -p "Pressione ENTER após configurar..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 7: Iniciar add-on"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "No add-on:"
echo "  1. Ir à tab: Info"
echo "  2. Clicar: START"
echo "  3. Aguardar inicialização (15-30 segundos)"
echo "  4. Ir à tab: Log"
echo "  5. Verificar mensagens:"
echo ""
echo "✅ Logs esperados:"
echo "  [INFO] Starting GitHub MCP Server..."
echo "  [INFO] Configuration:"
echo "  [INFO]   Toolsets: repos,issues,pull_requests,projects"
echo "  [INFO]   Port: 8080"
echo "  [INFO] Pulling GitHub MCP Server Docker image..."
echo "  [INFO] Starting FastAPI HTTP wrapper..."
echo ""
read -p "Pressione ENTER se logs estão OK..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASSO 8: Testar funcionamento"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "No terminal do HAOS (via SSH):"
echo ""
echo "  curl http://localhost:8080/health"
echo ""
echo "✅ Resposta esperada:"
echo '  {"status":"healthy","docker_accessible":true,"version":"1.0.0"}'
echo ""
read -p "Teste o comando acima e pressione ENTER se funcionou..."
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ INSTALAÇÃO COMPLETA!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎉 O add-on está instalado e a funcionar!"
echo ""
echo "Próximos passos:"
echo "  1. Configurar VSCode (ver: docs/vscode-setup.md)"
echo "  2. Criar SSH tunnel:"
echo "     ssh -L 8080:localhost:8080 root@homeassistant.local"
echo "  3. Testar com GitHub Copilot"
echo ""
echo "📚 Documentação:"
echo "  • LEIAME_PT.md - Guia completo (PT)"
echo "  • README.md - Documentação principal (EN)"
echo "  • BUGFIX.md - Detalhes das correções"
echo ""
echo "🆘 Problemas?"
echo "  • Verificar logs: Supervisor → GitHub MCP Server → Log"
echo "  • Consultar: BUGFIX.md (secção Troubleshooting)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
